# This config file is for Sonarqube only
name: Sonar
description: Sonar

publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^3.4.0

flutter:
  generate: true
  uses-material-design: true

workspace:
  - app
  - modules/domain
  - modules/data
  - modules/common